export const mockData = [
    {
        filename: '2024-001-杭州湾跨海大桥南航道桥C30混凝土强度检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-001',
            reportType: '工程现场抽查',
            projectName: '杭州湾跨海大桥南航道桥主体结构工程',
            testDate: '2024-03-15',
            strength_grade: 'C30',
            actual_strength: 35.2,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 350 m²/kg',
            water_cement_ratio: 0.45,
            aggregate_info: '碎石5-25mm连续级配，含泥量0.8%',
            admixture: '聚羧酸高效减水剂，掺量1.2%',
            curing_condition: '标准养护，温度20±2°C，湿度95%以上',
            curing_age: '28天',
            test_method: 'GB/T 50107-2010 混凝土强度检验评定标准',
            conclusion: '合格',
            // 影响因素分析数据（关键参数）
            strength_factors: {
                // 关键参数1: 水泥用量 (kg/m³)
                cement_content: 380,
                // 关键参数2: 水灰比
                water_cement_ratio: 0.45,
                // 关键参数3: 高效减水剂掺量 (%)
                water_reducer_dosage: 1.2,
                // 关键参数4: 养护温度×龄期（成熟度）
                curing_temperature: 20, // °C
                curing_days: 28, // 天
                curing_maturity: 560, // 成熟度 = 温度 × 龄期
                // 关键参数5: 粉煤灰/矿渣掺量 (%)
                fly_ash_dosage: 15, // 粉煤灰掺量
                slag_dosage: 10, // 矿渣掺量
                // 关键参数6: 粗骨料用量 (kg/m³)
                coarse_aggregate_content: 1100,
                // 关键参数7: 细骨料用量 & 砂率
                fine_aggregate_content: 650, // 细骨料用量 (kg/m³)
                sand_ratio: 37, // 砂率 (%)
                // 其他参数
                cement_strength_grade: 42.5,
                cement_fineness_value: 350,
                curing_humidity: 95,
                curing_method: '标准养护',
                strength_development: {
                    day_3: 18.5,
                    day_7: 25.2,
                    day_14: 30.8,
                    day_28: 35.2,
                },
            },
        },
    },
    {
        filename: '2024-002-北京大兴国际机场综合服务楼地下室C35混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-002',
            reportType: '委托检测',
            projectName: '北京大兴国际机场综合服务楼地下室防水工程',
            testDate: '2024-03-18',
            strength_grade: 'C35',
            actual_strength: 38.5,
            cement_type: '普通硅酸盐水泥P.O 42.5R（早强型）',
            cement_fineness: '比表面积 380 m²/kg',
            water_cement_ratio: 0.4,
            aggregate_info: '碎石5-31.5mm二级配，含泥量0.5%，针片状含量8%',
            admixture: '聚羧酸高效减水剂1.5%，引气剂0.02%',
            curing_condition: '标准养护，温度20±2°C，湿度≥95%',
            curing_age: '28天',
            test_method: 'GB/T 50081-2019 混凝土物理力学性能试验方法标准',
            conclusion: '合格，抗压强度满足设计要求',
            strength_factors: {
                cement_content: 400,
                water_cement_ratio: 0.4,
                water_reducer_dosage: 1.5,
                curing_temperature: 20,
                curing_days: 28,
                curing_maturity: 560,
                fly_ash_dosage: 12,
                slag_dosage: 8,
                coarse_aggregate_content: 1120,
                fine_aggregate_content: 660,
                sand_ratio: 37,
                cement_strength_grade: 42.5,
                cement_fineness_value: 380,
                curing_humidity: 95,
                curing_method: '标准养护',
                strength_development: {
                    day_3: 20.5,
                    day_7: 27.8,
                    day_14: 33.2,
                    day_28: 38.5,
                },
            },
        },
    },
    {
        filename: '2024-003-沪宁高速公路扩建工程太湖大桥C40混凝土强度检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-003',
            reportType: '工程现场抽查',
            projectName: '沪宁高速公路扩建工程太湖大桥主桥墩台',
            testDate: '2024-03-20',
            strength_grade: 'C40',
            actual_strength: 44.8,
            cement_type: '矿渣硅酸盐水泥P.S.A 42.5',
            cement_fineness: '比表面积 360 m²/kg',
            water_cement_ratio: 0.38,
            aggregate_info: '玄武岩碎石5-25mm连续级配，含泥量0.3%，针片状含量5%',
            admixture: '聚羧酸高效减水剂1.8%，缓凝剂0.3%',
            curing_condition: '现场覆盖洒水养护，温度18-25°C',
            curing_age: '28天',
            test_method: 'JTG 3420-2020 公路工程水泥及水泥混凝土试验规程',
            conclusion: '优良，强度超过设计值10%以上',
            strength_factors: {
                cement_content: 410,
                water_cement_ratio: 0.38,
                water_reducer_dosage: 1.8,
                curing_temperature: 20,
                curing_days: 28,
                curing_maturity: 560,
                fly_ash_dosage: 14,
                slag_dosage: 10,
                coarse_aggregate_content: 1150,
                fine_aggregate_content: 670,
                sand_ratio: 37,
                cement_strength_grade: 42.5,
                cement_fineness_value: 360,
                curing_humidity: 90,
                curing_method: '现场覆盖养护',
                strength_development: {
                    day_3: 22.5,
                    day_7: 31.0,
                    day_14: 38.2,
                    day_28: 44.8,
                },
            },
        },
    },
    {
        filename: '2024-004-深圳平安金融中心T2塔楼核心筒C50高强混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-004',
            reportType: '委托检测',
            projectName: '深圳平安金融中心T2塔楼核心筒剪力墙',
            testDate: '2024-03-22',
            strength_grade: 'C50',
            actual_strength: 55.6,
            cement_type: '普通硅酸盐水泥P.O 52.5',
            cement_fineness: '比表面积 400 m²/kg',
            water_cement_ratio: 0.32,
            aggregate_info: '花岗岩碎石5-25mm连续级配，含泥量0.2%，针片状含量3%',
            admixture: '聚羧酸高效减水剂2.0%，硅灰掺量8%',
            curing_condition: '标准养护室，温度20±2°C，湿度98%',
            curing_age: '28天',
            test_method: 'GB/T 50081-2019',
            conclusion: '合格，高强混凝土质量优良',
            strength_factors: {
                cement_content: 450,
                water_cement_ratio: 0.32,
                water_reducer_dosage: 2.0,
                curing_temperature: 20,
                curing_days: 28,
                curing_maturity: 560,
                fly_ash_dosage: 18,
                slag_dosage: 12,
                coarse_aggregate_content: 1180,
                fine_aggregate_content: 690,
                sand_ratio: 37,
                cement_strength_grade: 52.5,
                cement_fineness_value: 400,
                curing_humidity: 98,
                curing_method: '标准养护',
                strength_development: {
                    day_3: 28.5,
                    day_7: 42.0,
                    day_14: 50.2,
                    day_28: 55.6,
                },
            },
        },
    },
    {
        filename: '2024-005-广州地铁18号线横沥站主体结构C30抗渗混凝土现场检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-005',
            reportType: '工程现场抽查',
            projectName: '广州地铁18号线横沥站主体结构底板',
            testDate: '2024-03-25',
            strength_grade: 'C30（P6抗渗）',
            actual_strength: 34.8,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 360 m²/kg',
            water_cement_ratio: 0.48,
            aggregate_info: '河卵石5-31.5mm二级配，含泥量0.6%',
            admixture: '聚羧酸减水剂1.0%，膨胀剂10%，引气剂0.015%',
            curing_condition: '洞内自然养护，温度15-20°C，湿度85-90%',
            curing_age: '28天',
            test_method: 'GB/T 50081-2019、GB/T 50082-2009 抗渗性能试验',
            conclusion: '抗压强度合格，抗渗等级达到P6',
            strength_factors: {
                cement_content: 370,
                water_cement_ratio: 0.48,
                water_reducer_dosage: 1.0,
                curing_temperature: 18,
                curing_days: 28,
                curing_maturity: 504,
                fly_ash_dosage: 15,
                slag_dosage: 10,
                coarse_aggregate_content: 1100,
                fine_aggregate_content: 650,
                sand_ratio: 37,
                cement_strength_grade: 42.5,
                cement_fineness_value: 360,
                curing_humidity: 88,
                curing_method: '洞内自然养护',
                strength_development: {
                    day_3: 18.4,
                    day_7: 25.1,
                    day_14: 30.6,
                    day_28: 34.8,
                },
            },
        },
    },
    {
        filename: '2024-006-三峡水库移民安置工程黄陵大坝C25混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-006',
            reportType: '委托检测',
            projectName: '三峡水库移民安置工程黄陵大坝除险加固',
            testDate: '2024-03-28',
            strength_grade: 'C25',
            actual_strength: 28.9,
            cement_type: '中热硅酸盐水泥M.H 42.5',
            cement_fineness: '比表面积 330 m²/kg',
            water_cement_ratio: 0.5,
            aggregate_info: '碎石5-40mm三级配，含泥量1.0%',
            admixture: '木质素系减水剂0.8%，缓凝剂0.5%',
            curing_condition: '现场覆盖养护，温度12-18°C',
            curing_age: '28天',
            test_method: 'SL 352-2020 水工混凝土试验规程',
            conclusion: '合格，满足水工建筑物要求',
        },
    },
    {
        filename: '2024-007-上海中心大厦二期裙楼C60超高强混凝土检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-007',
            reportType: '工程现场抽查',
            projectName: '上海中心大厦二期裙楼框架柱（地下5层）',
            testDate: '2024-04-01',
            strength_grade: 'C60',
            actual_strength: 67.2,
            cement_type: '普通硅酸盐水泥P.O 52.5R',
            cement_fineness: '比表面积 420 m²/kg',
            water_cement_ratio: 0.28,
            aggregate_info: '玄武岩碎石5-20mm连续级配，含泥量0.1%，针片状含量2%',
            admixture: '聚羧酸高效减水剂2.5%，硅灰10%，粉煤灰15%',
            curing_condition: '标准养护，温度20±1°C，湿度99%',
            curing_age: '28天',
            test_method: 'GB/T 50081-2019',
            conclusion: '优良，超高强混凝土性能卓越',
        },
    },
    {
        filename: '2024-008-成都天府国际机场T2航站楼道面C40抗冻混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-008',
            reportType: '委托检测',
            projectName: '成都天府国际机场T2航站楼站坪道面',
            testDate: '2024-04-03',
            strength_grade: 'C40（F200抗冻）',
            actual_strength: 45.3,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 370 m²/kg',
            water_cement_ratio: 0.35,
            aggregate_info: '玄武岩碎石5-31.5mm二级配，含泥量0.2%，针片状含量4%',
            admixture: '聚羧酸高效减水剂2.2%，引气剂0.05%（含气量4.5%）',
            curing_condition: '标准养护，温度20±2°C，湿度≥95%',
            curing_age: '28天',
            test_method: 'MH/T 5011-2019 民用机场水泥混凝土道面施工技术规范',
            conclusion: '合格，抗冻融循环200次后强度损失<5%',
        },
    },
    {
        filename: '2024-009-秦岭终南山公路隧道二次衬砌C30混凝土现场检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-009',
            reportType: '工程现场抽查',
            projectName: '秦岭终南山公路隧道二次衬砌工程K15+300',
            testDate: '2024-04-05',
            strength_grade: 'C30',
            actual_strength: 33.5,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 355 m²/kg',
            water_cement_ratio: 0.46,
            aggregate_info: '碎石5-31.5mm二级配，含泥量0.7%',
            admixture: '萘系高效减水剂1.5%，早强剂2%',
            curing_condition: '隧道内自然养护，温度10-15°C，湿度80%',
            curing_age: '28天',
            test_method: 'JTG 3420-2020',
            conclusion: '合格，但养护湿度略低影响后期强度发展',
        },
    },
    {
        filename: '2024-010-辽宁红沿河核电站4号机组安全壳C55混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-010',
            reportType: '委托检测',
            projectName: '辽宁红沿河核电站4号机组安全壳结构',
            testDate: '2024-04-08',
            strength_grade: 'C55',
            actual_strength: 61.8,
            cement_type: '低热硅酸盐水泥L.H 42.5',
            cement_fineness: '比表面积 340 m²/kg',
            water_cement_ratio: 0.33,
            aggregate_info: '花岗岩碎石5-25mm连续级配，含泥量0.1%，针片状含量2%',
            admixture: '聚羧酸高效减水剂2.3%，粉煤灰20%，矿渣粉15%',
            curing_condition: '标准养护，温度20±1°C，湿度98%，养护90天',
            curing_age: '90天',
            test_method: 'GB/T 50081-2019、NB/T 20007-2012 核电厂混凝土结构技术规程',
            conclusion: '优秀，各项指标均超过核电标准要求',
        },
    },
    {
        filename: '2024-011-宁波舟山港梅山港区6号泊位C40海工混凝土现场检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-011',
            reportType: '工程现场抽查',
            projectName: '宁波舟山港梅山港区6号泊位10万吨级码头',
            testDate: '2024-04-10',
            strength_grade: 'C40（海工混凝土）',
            actual_strength: 46.2,
            cement_type: '抗硫酸盐硅酸盐水泥P.S.R 42.5',
            cement_fineness: '比表面积 375 m²/kg',
            water_cement_ratio: 0.38,
            aggregate_info: '玄武岩碎石5-31.5mm二级配，含泥量0.3%，氯离子含量0.02%',
            admixture: '聚羧酸高效减水剂1.8%，硅灰6%，阻锈剂1.5%',
            curing_condition: '海水环境自然养护，温度15-22°C',
            curing_age: '28天',
            test_method: 'JTS/T 236-2019 海港工程混凝土结构防腐蚀技术规范',
            conclusion: '合格，抗氯离子渗透性能优良',
        },
    },
    {
        filename: '2024-012-哈尔滨万达茂住宅项目冬季施工C35混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-012',
            reportType: '委托检测',
            projectName: '哈尔滨万达茂住宅项目A区主体结构',
            testDate: '2024-01-15',
            strength_grade: 'C35',
            actual_strength: 32.8,
            cement_type: '普通硅酸盐水泥P.O 42.5R（早强型）',
            cement_fineness: '比表面积 390 m²/kg',
            water_cement_ratio: 0.42,
            aggregate_info: '碎石5-25mm连续级配，含泥量0.6%',
            admixture: '聚羧酸高效减水剂2.0%，早强剂3%，防冻剂5%',
            curing_condition: '保温养护，环境温度-5°C，覆盖保温被',
            curing_age: '28天',
            test_method: 'JGJ/T 104-2011 建筑工程冬期施工规程',
            conclusion: '基本合格，但强度略低于设计值，建议延长养护时间',
        },
    },
    {
        filename: '2024-013-广东珠海横琴口岸联检大楼夏季高温C30混凝土现场检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-013',
            reportType: '工程现场抽查',
            projectName: '广东珠海横琴口岸联检大楼主体结构',
            testDate: '2024-07-20',
            strength_grade: 'C30',
            actual_strength: 31.5,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 365 m²/kg',
            water_cement_ratio: 0.48,
            aggregate_info: '碎石5-31.5mm二级配，含泥量0.8%',
            admixture: '聚羧酸减水剂1.2%，缓凝剂1.0%',
            curing_condition: '洒水养护，环境温度32-38°C，湿度60%',
            curing_age: '28天',
            test_method: 'JGJ/T 232-2011 建筑工程夏期施工技术规范',
            conclusion: '合格，但因高温和湿度不足，后期强度增长受限',
        },
    },
    {
        filename: '2024-014-中建科技装配式建筑产业基地预制构件C45混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-014',
            reportType: '委托检测',
            projectName: '中建科技装配式建筑产业基地预制梁板构件',
            testDate: '2024-04-12',
            strength_grade: 'C45',
            actual_strength: 50.2,
            cement_type: '普通硅酸盐水泥P.O 42.5R',
            cement_fineness: '比表面积 385 m²/kg',
            water_cement_ratio: 0.36,
            aggregate_info: '碎石5-25mm连续级配，含泥量0.4%，针片状含量5%',
            admixture: '聚羧酸高效减水剂2.0%，早强剂1%',
            curing_condition: '蒸汽养护，升温2h至65°C，恒温6h，降温2h',
            curing_age: '1天（蒸养）+ 27天标养',
            test_method: 'GB/T 51231-2016 装配式混凝土建筑技术标准',
            conclusion: '优良，蒸汽养护效果显著，早期强度高',
        },
    },
    {
        filename: '2024-015-雄安新区容东片区绿色建筑示范项目再生骨料C25混凝土现场检测报告.pdf',
        extractContent: {
            reportNumber: 'JC-2024-015',
            reportType: '工程现场抽查',
            projectName: '雄安新区容东片区绿色建筑示范项目B地块',
            testDate: '2024-04-15',
            strength_grade: 'C25',
            actual_strength: 27.3,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 360 m²/kg',
            water_cement_ratio: 0.52,
            aggregate_info: '再生骨料取代率30%，5-31.5mm二级配，含泥量1.5%',
            admixture: '聚羧酸减水剂1.5%，增强剂2%',
            curing_condition: '标准养护，温度20±2°C，湿度≥95%',
            curing_age: '28天',
            test_method: 'GB/T 25177-2010 混凝土用再生粗骨料',
            conclusion: '合格，再生骨料混凝土强度略低但满足要求',
        },
    },
    {
        filename: '2024-016-天津周大福金融中心异形结构自密实C40混凝土委托检测报告.pdf',
        extractContent: {
            reportNumber: 'WT-2024-016',
            reportType: '委托检测',
            projectName: '天津周大福金融中心复杂异形钢管混凝土柱',
            testDate: '2024-04-18',
            strength_grade: 'C40（自密实）',
            actual_strength: 44.6,
            cement_type: '普通硅酸盐水泥P.O 42.5',
            cement_fineness: '比表面积 380 m²/kg',
            water_cement_ratio: 0.4,
            aggregate_info: '碎石5-20mm连续级配（小粒径），含泥量0.3%',
            admixture: '聚羧酸高效减水剂2.8%，粘度改性剂0.8%，粉煤灰25%，矿粉20%',
            curing_condition: '标准养护，温度20±2°C，湿度≥95%',
            curing_age: '28天',
            test_method: 'JGJ/T 283-2012 自密实混凝土应用技术规程',
            conclusion: '优良，扩展度670mm，抗压强度优异',
        },
    },
];
